### ISSUE TITLE
Smoother transition animations on the new UI example theme.

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#103]
### Description
In order to make the experience of using the new UI them more appealing and trustworthy, the transitions between steps in the flow should be smoother.

###Tasks

- [ ] When clicking a button, make it so that the during the transition animation the background remains black instead of disappearing.

###Examples and references
Enter: https://examples-future.ballerine.app/ and see the colors and texts throughout the flow.

**Comment by tejash023** [comment]
Hey, Can I work on this?

**Comment by alonp99** [comment]
@tejash023 Sorry, missed your comment - sure, we are available in slack for questions

**Comment by alonp99** [comment]
Closing as web-sdk in under massive refactor, this will probably not be relevant
