### ISSUE TITLE
Case management full screen image modal is not showing.

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#106]
### Description
Case management dashboard zoom on previewed image is not working.

### Has the bug been reported before
No.

### Expected Behaviour
Once you click on the image which is presented in the large image viewer, a modal should pop up, showing the image in full screen.
This behaviour was already implemented but it seems something prevents it from happening.

### Actual Behaviour
Clicking the image doesn't do anything.

### Environment
On https://www.backoffice-demo.ballerine.app/case-management
All browsers

### Steps to Reproduce
1. Enter https://www.backoffice-demo.ballerine.app/case-management
2. Click on the big image on the right side of the screen.
3. Modal is not showing

**Comment by alonp99** [comment]
Fixed on backoffice v2
