### ISSUE TITLE
BSA filing - SAR reports

### ISSUE THREAD

**Issue by Appura1** [ballerine-io/ballerine#129]
### Description
Do you plan to integrate with Fincen for e-filing SAR reports?

https://bsaefiling.fincen.treas.gov/

**Comment by nitzanballerine** [comment]
Hi @Appura1 ,
SAR is definitely something that our system should help with.
Currently, we are working on the infrastructure that will make it easy to add integrations and data flows.
Afterward, we will do the integration to enable automating SAR from the back office and workflow engine.
