### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by dwi11harsh** [ballerine-io/ballerine#1404]
### Description
Upon running 
`pnpm kyc-manual-review-example`
the code breaks
error message shows that it was unable to connect to docker daemon but it is up and running on the system

### Expected Behaviour
2 tabs should have opened
http://localhost:5173/ 
http://localhost:5137/

### Actual Behaviour
Error message- 
```
ELIFECYCLE  Command failed with exit code 125.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target setup for project @ballerine/workflows-service (932ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

```

### Steps to Reproduce
1. clone ballerine locally.
2. run `pnpm install`
3. run `pnpm monorepo:init`
4. run `pnpm kyc-manual-review-example`

**Comment by l4rot** [comment]
Hey, hope I am not too late. Had a similar error and it was due to the fact that there was already a docker container running with the same port. So you have to basically stop the docker container that is running on that port and it should resolve the issue for you 👍
