### ISSUE TITLE
[BAL-508] [BAL-507] Move json schemas to typebox in the collection flow

### ISSUE THREAD

**Issue by alonp99** [ballerine-io/ballerine#1422]
- Start with a test to check that the typebox output is 1to1 as the json schema, import the typebox instead of json schema
- Potential issue, we added some custom properties to the json schema (for validation purposes with ajv - for example errorMessages, formats etc..) - we need to find a way to add those to typebox as well

relevant files: services/workflows-service/src/ui-definition/utils/collection-flow/

<sub>From [SyncLinear.com](https://synclinear.com) | [BAL-507](https://linear.app/ballerine/issue/BAL-507/move-json-schemas-to-typebox-in-the-collection-flow)</sub>

<sub>[BAL-508](https://linear.app/ballerine/issue/BAL-508/[bal-507]-move-json-schemas-to-typebox-in-the-collection-flow)</sub>

**Comment by his-maj-esty** [comment]
@alonp99 please elaborate the issue. I want to work on it.

**Comment by alonp99** [comment]
@his-maj-esty Hey, ive added some content to the description, feel free to reach out in slack for any questions. thanks for contributing !
