### ISSUE TITLE
DB Connection Error

### ISSUE THREAD

**Issue by saadmajeed01** [ballerine-io/ballerine#1845]
While implementing this repository, facing below error and couldn't found any solution to resolve this.

Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `admin` are not valid.
Please make sure to provide valid database credentials for the database server at `localhost`.
 ELIFECYCLE  Command failed with exit code 1.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target setup for project @ballerine/workflows-service (16s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]

 ELIFECYCLE  Command failed with exit code 1.

**Comment by 18Blank23** [comment]
how did you fix it?
