### ISSUE TITLE
Not Support On Windows

### ISSUE THREAD

**Issue by yogeshacharya** [ballerine-io/ballerine#1982]
I run from kyb and fill all the details then submit the from. Into admin form it shows me Internal Server Error (500) anytime.
It shows me different data into admin form too.  I submitted the issue into slack support group too.

I have attached the text file which shown into console.
[Console Error.txt](https://github.com/ballerine-io/ballerine/files/13978878/Console.Error.txt)

**Comment by saadmajeed01** [comment]
Hello, Can somebody help and tell me how to resolve this error?
While running the **"pnpm kyb-manual-review-example"** command, I am facing this error. 


Applying migration `20230723221706_add_jsonb_deep_merge_with_options`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20230723221706_add_jsonb_deep_merge_with_options

Database error code: XX000

Database error:
ERROR: SyntaxError: Unexpected token >
DETAIL: jsonb_deep_merge_with_options() LINE 2:   const mergeObjects = (obj1, obj2) => {

DbError { severity: "ERROR", parsed_severity: None, code: SqlState(EXX000), message: "SyntaxError: Unexpected token >", detail: Some("jsonb_deep_merge_with_options() LINE 2:   const mergeObjects = (obj1, obj2) => {"), hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("plv8.cc"), line: Some(1649), routine: Some("rethrow") }

 ELIFECYCLE  Command failed with exit code 1.
