### ISSUE TITLE
Database error code: XX000 (Applying migration `20230723221706_add_jsonb_deep_merge_with_options`)

### ISSUE THREAD

**Issue by saadmajeed01** [ballerine-io/ballerine#2006]
Hello, Can somebody help and tell me how to resolve this error?
While running the **"pnpm kyb-manual-review-example"** command, I am facing this error. 

Applying migration `20230723221706_add_jsonb_deep_merge_with_options`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20230723221706_add_jsonb_deep_merge_with_options

Database error code: XX000

Database error:
ERROR: SyntaxError: Unexpected token >
DETAIL: jsonb_deep_merge_with_options() LINE 2:   const mergeObjects = (obj1, obj2) => {

DbError { severity: "ERROR", parsed_severity: None, code: SqlState(EXX000), message: "SyntaxError: Unexpected token >", detail: Some("jsonb_deep_merge_with_options() LINE 2:   const mergeObjects = (obj1, obj2) => {"), hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("plv8.cc"), line: Some(1649), routine: Some("rethrow") }

 ELIFECYCLE  Command failed with exit code 1.

**Comment by alonp99** [comment]
Hi @saadmajeed01 ,
What you're missing is the plv8 extension installed on your postgres instance. we use a docker image which includes it already across the project "sibedge/postgres-plv8:15.3-3.1.7" (deploy/docker-compose.yml:71)

I recommend using the pre-made dockerfiles and docker compose scripts to run the project, they already include all the dependencies.

if you still have issues feel free to reach out on slack, you can find the link in the readme

**Comment by saadmajeed01** [comment]
> postgres-plv8

Can you help me resolve this issue as I am not understanding Docker at all?

**Comment by alonp99** [comment]
ill need to understand better your setup to help you efficiently - ping me on our slack workspace
