### ISSUE TITLE
Bug - Cannot deploy ballerine on aws instance

### ISSUE THREAD

**Issue by pratapalakshmi** [ballerine-io/ballerine#2050]
Upon deploying ballerine on AWS 
We are seeing the following errors and which causes issues in deploying and using ballerine
![image](https://github.com/ballerine-io/ballerine/assets/137189067/2e98c766-adf3-44c3-9455-68eab4a6c27d)

More details:
```
BACKOFFICE_CORS_ORIGIN: http://localhost:5137
WORKFLOW_DASHBOARD_CORS_ORIGIN: http://localhost:5200
KYB_EXAMPLE_CORS_ORIGIN: http://localhost:5201
```

![image](https://github.com/ballerine-io/ballerine/assets/137189067/36b8ce4b-8885-4fc3-8410-8a495492719b)

**Comment by TheMatzy** [comment]
Same problem here....

**Comment by dzbrody** [comment]
We have tried to run on EC2 as well and had a similar issue. Is there instruction somewhere for AWS EC2 or Google cloud?

**Comment by CatDTran** [comment]
Same problem. I think if this is run on a remote server and not a local machine, and when we try to connect it from a local machine, the browser try to load http://localhost:3000/api/v1/internal/auth/session, it simply won't work because the browser is trying to connect to localhost which is not where the application is running on. Perhaps, there should be a way to set the domain?

**Comment by pratapalakshmi** [comment]
@TheMatzy , @CatDTran  and @dzbrody We are coming with docs and we shall share it at the earliest. 

In the time being i request you to try the following steps.

```
ubuntu@ip-172-xyx:~/ballerine/deploy$ cat .env
DOMAIN_NAME=gpdev.eu-central-1.ballerine.io
VITE_API_URL=http://<domain>:3000/api/v1/
VITE_KYB_DEFINITION_ID=kyb_parent_kyc_session_example
BACKOFFICE_PORT=5137
HEADLESS_SVC_PORT=5173
WORKFLOW_SVC_PORT=3000
BCRYPT_SALT=10
API_KEY=secret
NODE_ENV=development
COMPOSE_PROJECT_NAME=ballerine-x
DB_PORT=5432
DB_USER=admin
DB_PASSWORD=admin
SESSION_SECRET=secret
SESSION_EXPIRATION_IN_MINUTES=60
BACKOFFICE_CORS_ORIGIN=http://<domain>:5137
WORKFLOW_DASHBOARD_CORS_ORIGIN=http://<domain>:5200
KYB_EXAMPLE_CORS_ORIGIN=http://<domain>:5201
WORKFLOW_DASHBOARD_PORT=5200
WEBSOCKET_SVC_PORT=3500
KYB_APP_PORT=5201
WEBHOOK_SECRET=webhook_secret
APP_API_URL=https://alon.ballerine.dev
EMAIL_API_URL=https://api.sendgrid.com/v3/mail/send
UNIFIED_API_URL=https://unified-api-test.eu.ballerine.app
ENVIRONMENT_NAME=development
```
Update the client-build
```
ubuntu@ip-172-xyx:~/ballerine/apps/backoffice-v2$ cat .env.example
VITE_API_URL=http://<domain>:3000/api/v1/internal
VITE_API_KEY=secret
VITE_AUTH_ENABLED=true
VITE_MOCK_SERVER=false
VITE_POLLING_INTERVAL=10
VITE_ASSIGNMENT_POLLING_INTERVAL=5
VITE_FETCH_SIGNED_URL=false
```

Finally start using 
```
sudo docker-compose -f docker-compose-build.yml up -d
```

**Comment by ludmorales** [comment]
Same problem here in a GCP vm, 
![Screenshot 2024-02-19 at 00 31 19](https://github.com/ballerine-io/ballerine/assets/92339538/d4a63bd1-414c-4ec0-9696-26291a75f87b)

**Comment by ludmorales** [comment]
Hi team, 

After changing from "localhost" to a public IP/Domain in the .env.example file, I see the following error: 
![Screenshot 2024-02-19 at 09 07 33](https://github.com/ballerine-io/ballerine/assets/92339538/fef37853-632f-40dd-99ac-6a3cf93e05ac)

**Comment by dzbrody** [comment]
> BACKOFFICE_CORS_ORIGIN=http://<domain>:5137
> WORKFLOW_DASHBOARD_CORS_ORIGIN=http://<domain>:5200
> KYB_EXAMPLE_CORS_ORIGIN=http://<domain>:5201

What is the definition for KYC, pls
