### ISSUE TITLE
npm published package of web-ui-sdk is not including the dist folder and files

### ISSUE THREAD

**Issue by jalamprea** [ballerine-io/ballerine#2118]
### Description
SInce the web-ui-sdk package is not using a .npmignore file, when the npm publish script runs it's publishing into npm without the dist folders so the final package when users install it is empty.
If you install the package using the command `npm install --save @ballerine/web-ui-sdk` just like the documentation says, and then import into your JS app, it will not work.
The line `import { flows as ballerineFlows } from '@ballerine/web-ui-sdk'` will show an error because the package is not including the dist folder with the module built.

### Has the bug been reported before
No

### Expected Behaviour
On npm run publish:patch script is running and publishing a new version of the package into npm website, it should include the dist folder, so when users install the package from npm it will include the dist folder.

### Actual Behaviour
The package is publishing into npm without the dist folder, so its being empty

### Environment
* Version of the affected apps and packages:
  web-ui-sdk@1.4.39

### Steps to Reproduce
1. on a Javascript project, install the package: `npm install --save @ballerine/web-ui-sdk`
2. Import into your app: `import { flows as ballerineFlows } from '@ballerine/web-ui-sdk'`

### Any possible solutions
Add the .npmignore file into the web-ui-sdk folder without the dist folder, so when a new version of the package is published into npm it will include the proper files. This will prevent the `dist` folder is excluded because it's part of the .gitignore file

### If the bug is confirmed, would you be willing to submit a PR
Yes

### Screenshots
![image](https://github.com/ballerine-io/ballerine/assets/3508660/3b7f29a3-9aa7-4770-97ba-00d4422eb4b2)
![image](https://github.com/ballerine-io/ballerine/assets/3508660/7e6d87c5-7154-48fd-8ba9-548d2c58d247)

**Comment by alonp99** [comment]
@jalamprea thanks for the heads up.

you can go ahead and open a PR for it, ill make sure its merged asap
