### ISSUE TITLE
Name change: `sdks/web-sdk` to `sdks/web-ui-sdk`

### ISSUE THREAD

**Issue by alonp99** [ballerine-io/ballerine#226]
Search for web-sdk reference

Known locations:
* folder name
* web-sdk package.json name
* monorepo root scripts
* vite config
* Readme's

**Comment by RohanJacob23** [comment]
Hello @alonp99,

I'm interested in contributing to this issue. Do I need to replace 'web-sdk' with 'web-ui-sdk' throughout the 'sdks' folder?

**Comment by alonp99** [comment]
Hey @RohanJacob23 , thanks for contributing 

Yes you will need to the change the name and the reference across the project (not only the sdks folder)

**Comment by RohanJacob23** [comment]
Thank you for your response, @alonp99. 
I will start working on the issue as soon as possible.

**Comment by RohanJacob23** [comment]
Hi @alonp99,

Sorry to bother you, but I wanted to ask if I also need to change the name in the CSS files?
