### ISSUE TITLE
Create enum `WorkflowRuntimeDataStatus`

### ISSUE THREAD

**Issue by MatanYadaev** [ballerine-io/ballerine#274]
Convert WorkflowRuntimeData's status column from a string into an enum in the `schema.prisma` file.

**Comment by N-NeelPatel** [comment]
@MatanYadaev - If this issue is fixed. can you please close this issue.

**Comment by MatanYadaev** [comment]
Hi @N-NeelPatel. We close issues only when the code is live on `main`.
Usually, merge cycles from `dev` to `main` will be much shorter than this time.
