### ISSUE TITLE
Remove "strict: false" in Ajv config, make risk-score flow run successfully

### ISSUE THREAD

**Issue by alonp99** [ballerine-io/ballerine#313]

**Comment by alonp99** [comment]
Hey @Chiadikaobixo are you still taking this one?

**Comment by Chiadikaobixo** [comment]
Good day @alonp99 I am just seeing your message. I forgot  I assigned this task to myself, due to personal reasons I cannot be able to take it up at this point in time. I look forward to start contributing again in no due time. thanks.
