### ISSUE TITLE
Primary button not working on large height screen phones

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#40]
**Issue**
Something breaks in the layout and prevents the primary button from being clickable on mobile when the phone's screen height is above a certain size.
**How to reproduce**
- Open the flow
- On the first screen open "Inspect element"
- Change the view to "iPhone XR" (happened on other views as well)
- Try clicking the button > doesn't work
- then change the view to "iPhone SE"
- Try clicking the button > works

**Comment by TzlilSwimmer123** [comment]
@nitzanballerine I tried to reproduce this bug but it didn't happened to me. It's still happens to you?

**Comment by alonp99** [comment]
@TzlilSwimmer123 couldn't reproduce it as well, closing it for now.
