### ISSUE TITLE
Backoffice-v2: Change agent email in the bottom left to first name + last name

### ISSUE THREAD

**Issue by alonp99** [ballerine-io/ballerine#409]
![Screenshot 2023-05-23 at 20 51 20](https://github.com/ballerine-io/ballerine/assets/8467965/afae4eaf-66fa-475c-ad76-cd2155d05e96)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this

**Comment by dotarjun** [comment]
Hey @alonp99 could you let me know more about this issue. Maybe with a screenshot

**Comment by alonp99** [comment]
Hey @dotarjun , @tarunsamanta2k20 I've added a photo

ill assign @tarunsamanta2k20 for this one, @dotarjun ping me in slack so i can assign something that interests you

**Comment by tarunsamanta2k20** [comment]
@alonp99 I am getting the following error in localhost **Invariant failed: Could not find an active match from "/$locale/case-management/individuals/$endUserId"**.

**Comment by tarunsamanta2k20** [comment]
@alonp99 i am getting the following error on dev branch but not in main branch.

**Failed to resolve entry for package "@ballerine/common". The package may have incorrect main/module/exports specified in its package.json.**

**Comment by alonp99** [comment]
Hey @tarunsamanta2k20 make sure you build all packages with "pnpm build", if you move from between branches and get error try to run "pnpm run monorepo:init"

**Comment by tarunsamanta2k20** [comment]
@alonp99 http://localhost:5137/en/auth/sign-in asking for email id and password on dev branch.
