### ISSUE TITLE
Illustration SVGs seem small on large screens

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#41]
Right now it seems like the images take the size property from the one on the actual file.
this makes the images look small on large screens.
we can override the image size to be width 100%, and height 100% and it will fix it for all screens

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/109664420/198875922-4815cce1-3468-41af-ade0-2b83fc852a31.png">

**Comment by alonp99** [comment]
Closing as web-sdk in under massive refactor, this will probably not be relevant
