### ISSUE TITLE
Make the camera overly responsive and lightweight

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#42]
Try and see if with these properties we can make the overlay look good on every screen.

We can animate the border color of the overlay so the screen would feel more alive (like changing color from `border: 3px solid #ffffff4d;` to `border: 3px solid #007aff75;` and back.

Steps I did:

- remove previous overlay div
- added a div above the camera button
- added these properties:

Passport
---

**.overlay.card.svelte-10mpprx {**

    width: 100%;

**.overlay.svelte-10mpprx {**

    max-width: 80%;
    max-height: 100%;
    outline: 1000px solid #000000d6;
    border: 3px solid #ffffff4d;
    z-index: 1;
    border-radius: 12px;
    aspect-ratio: 3/4;

>`Still need to vertically center the div + make it so in small screens the text won't overlap with it`

-----

ID card / backside / drivers license
---

**.overlay.card.svelte-10mpprx {**

    width: 100%;

**.overlay.svelte-10mpprx {**

    max-width: 80%;
    max-height: 100%;
    outline: 1000px solid #000000d6;
    border: 3px solid #ffffff4d;
    z-index: 1;
    border-radius: 12px;
    aspect-ratio: 4/3;
    
>`Still need to vertically center the div`

-----

Selfie
---

**.overlay.card.svelte-10mpprx {**

    width: 100%;

**.overlay.svelte-10mpprx {**

    max-width: 80%;
    max-height: 100%;
    outline: 1000px solid #000000d6;
    border: 3px solid #ffffff4d;
    z-index: 1;
    border-radius: 100%;
    aspect-ratio: 3/4;

>`Still need to vertically center the div + make it so in small screens the text won't overlap with it`

**A4 doc**

**.overlay.card.svelte-10mpprx {**

    width: 100%;

**.overlay.svelte-10mpprx {**

    max-width: 90%;
    max-height: 100%;
    outline: 1000px solid #000000d6;
    border: 3px solid #ffffff4d;
    z-index: 1;
    border-radius: 12px;
    aspect-ratio: 3/4;

>`Still need to vertically center the div + make it so in small screens the text won't overlap with it`

**Comment by alonp99** [comment]
Closing as web-sdk in under massive refactor, this will probably not be relevant
