### ISSUE TITLE
Bug - when moving between views (from the navbar) the inner list filters reset to default

### ISSUE THREAD

**Issue by alonp99** [ballerine-io/ballerine#512]
Reproduce: (DEV BRANCH)

Run one of the examples, go to individuals view in the nav bar, change the list filters, then move to business view and back to individuals

you will see the filters are reset to default

Possible solution - save the last list filters per nav bar link (view filter) in localstorage

**Comment by Mindo-Joseph** [comment]
@alonp99 I would like to work on this, could you assign to me?

**Comment by alonp99** [comment]
@Mindo-Joseph Sorry missed your mesage

**Comment by Mindo-Joseph** [comment]
No problem, lemme get to it then

**Comment by alonp99** [comment]
@Mindo-Joseph Seems like @siddiqss already have some progress - let me know if another issue interests you
