### ISSUE TITLE
Case per document capability

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#525]
When a company wants to enable sending documents in order to improve a customer's score, agents will not care about the entire context of the user, and will only care if the current document they are reviewing is valid or not.
That means that we should enable that if a user has sent two documents, each one will have its own task.

**Comment by Omri-Levy** [comment]
Currently, we have logic that checks if there's an existing workflow, and if there is one, it is updated instead of creating a new workflow. We could add a config to control this behavior, in turn uploading a second document would create a new case.
