### ISSUE TITLE
Make switching camera easier / possible

### ISSUE THREAD

**Issue by Wombosvideo** [ballerine-io/ballerine#63]
## Description
Currently the default camera for taking ID card photos seems to be the selfie cam on my phone and I couldn't really find a way to switch it easily.

## Suggestion
- If the user has one camera, use that.
- If the user has two cameras, provide a button to switch, and use the more suitable camera by default (by checking it's name, if possible and detecting words like "Front", "Rear")
- If the user has more than two cameras, provide a dropdown to switch, and also try to suggest the most suitable one.

## Details
I tested using the live demo links in the repo.
Phone: OnePlus 7 Pro
Phone OS: Android 11 (stock)
Browser: Google Chrome 107.0

**Comment by alonp99** [comment]
Thanks @Wombosvideo, The basic functionality should open the correct camera per capture type (front for selfies and back for the others) seems like it doesn't work the same on all Android devices/Mobile chrome versions.
We will investigate and update.

Your suggestions make sense, Even though detecting the correct camera is the best UX I think having it as an option in the camera config to show the camera switch button can be useful in some cases. @nitzanballerine WDYT?

**Comment by nitzanballerine** [comment]
Thanks for pointing it out @Wombosvideo.
@alonp99 let's fix this bug first, I'll go ahead and define a definition for the "flip camera" option and multiple cameras functionalities.

**Comment by alonp99** [comment]
Closing as web-sdk in under massive refactor, this will probably not be relevant
