### ISSUE TITLE
Improvements for "No cases were found"

### ISSUE THREAD

**Issue by tomer-shvadron** [ballerine-io/ballerine#769]
## Description
When there are no cases, show a simple "No cases were found" message, in the case management.

## Design
On the case preview space, show a card with an illustration (attached), a Title, and a paragraph.

Design:
You can use [Shadcn](https://ui.shadcn.com/) for the necessary components and typography.
![image.png](https://images.zenhubusercontent.com/644101d59e3add200fa62732/3aae2053-a5e3-4ad4-ad6b-445a46a7d285)

Illustration:
![image.png](https://images.zenhubusercontent.com/644101d59e3add200fa62732/b6b61a3c-a1c4-4b6c-83c5-477b6e45f4dc)

Paragraph text:
```It looks like there aren't any cases in your queue right now.
What can you do now?
- Make sure to refresh or check back often for new cases.
- Ensure that your filters aren’t too narrow.
- If you suspect a technical issue, reach out to your technical team to diagnose the issue.

**Comment by SaumyaBhushan** [comment]
Hey @tomer-shvadron ! I would be interested to know more about this issue .

**Comment by nitzanballerine** [comment]
Hey @SaumyaBhushan , I've updated the information on this issue, let me know if you need any more information.

**Comment by tomer-shvadron** [comment]
Hi @SaumyaBhushan, I am taking this issue.

**Comment by siddiqss** [comment]
@tomer-shvadron are you done? If not, I can take this.

**Comment by tomer-shvadron** [comment]
Hi @siddiqss ! Thanks for offering but I had already finished this.

**Comment by tomer-shvadron** [comment]
Depends on #809
