### ISSUE TITLE
Add pending process indicator

### ISSUE THREAD

**Issue by Omri-Levy** [ballerine-io/ballerine#781]
- [ ] Add pending process indicator
        - [ ] See if a state of a child workflow matches a "pending_process" tag
        - [ ] Display a badge with the text of "Pending ID verification" in the KYC block

**Comment by alonp99** [comment]
@Omri-Levy please sync with tomer and make sure this tasks are covered in his tickets

**Comment by tomer-shvadron** [comment]
Depends on #1012
