### ISSUE TITLE
Better convey what the user inputted and what was a vendor response

### ISSUE THREAD

**Issue by alonp99** [ballerine-io/ballerine#827]
Secondary header that shows if the information is user-input or 3rd party info.
* user-provided input - we need to make sure  it doesn't get changed by 3rd party info
* 3rd party info - we need to find a generic way to differentiate between the collection flow and vendor information

Daniel says collection flow data does go into pluginsOutput 
Do vendors / plugins update context or entity?

**Comment by tomer-shvadron** [comment]
Depends on #1059
