### ISSUE TITLE
add support for multiple architectures like arm64 amd64 docker images for ballerine

### ISSUE THREAD

**Issue by gpushan** [ballerine-io/ballerine#879]
Currently, the images that are pushed to ghcr are amd64 image and it will not work directly in macbooks with m1 chip. Therefore it will be great if we can build images for both

**Comment by siddiqss** [comment]
Try using docker compose to build image for you system.
[Details here](https://github.com/ballerine-io/ballerine/tree/dev/deploy)

**Comment by pratapalakshmi** [comment]
@siddiqss This is more of automated task which will be done as part of github actions and push to github docker repo
