### ISSUE TITLE
Bug - Translations not working

### ISSUE THREAD

**Issue by BossBele** [ballerine-io/ballerine#97]
### Description
I have added translation overrides config for English & Swahili but can't seem to figure out how to change to other languages apart from English.

### Has the bug been reported before
N

### Expected Behaviour
A way to switch languages should be provided both - programmatically and through UI.

### Actual Behaviour
Text is overridden for default locale only (English).

### Environment
* Node version: v14.18.0
* Device, operating system and its version:
  * MacBook Pro 2017
  * MacOS Big Sur v11.6.5
* Browser and its version:
  * Chrome v108.0.5359.94 (Official Build) (x86_64)
* Version of the affected apps and packages:
  * next v13.0.6
  * react v18.2.0
  * @ballerine/web-sdk v1.1.38

### Steps to Reproduce
1. pnpm create next-app
2. pnpm add @ballerine/web-sdk
3. Initialize UI flow https://github.com/ballerine-io/ballerine#embedded-flows

### If the bug is confirmed, would you be willing to submit a PR
Maybe

**Comment by Omri-Levy** [comment]
Hey @BossBele, hope you're doing well. Currently locale can be changed by appending a query param of `?b_lang=sw` to the URL, with `sw` being any locale you've specified in your overrides. 

Otherwise, we're actively working on documentation and code examples which also cover translations. Let me know if there's anything else I could help with, or if you have any more questions!

**Comment by BossBele** [comment]
> Hey @BossBele, hope you're doing well. Currently locale can be changed by appending a query param of `?b_lang=sw` to the URL, with `sw` being any locale you've specified in your overrides.
> 
> Otherwise, we're actively working on documentation and code examples which also cover translations. Let me know if there's anything else I could help with, or if you have any more questions!

That solves my issue. Thanks!
