### ISSUE TITLE
Fix KYC polling

### ISSUE THREAD

**Issue by MatanYadaev** [ballerine-io/ballerine#986]
* `VITE_POLLING_INTERVAL` env variable is in charge of `react-query refetchInterval`
* Locally is set to 10 seconds. Need to check that it works locally in a E2E test
* If it works locally, check it's value in deployed environments
* If it doesn't work locally, check if `react-query staleTime` takes precedence or blocks it somehow (set for 10 seconds for workflows)
* If both aren't relevant to the problem and non-KYC polling works, need to check if there's a problem in the data we select when re-fetching

[User story](https://www.notion.so/ballerine/Polling-for-KYC-fcd5667407e84c82a14f5467d15a2b01?pvs=4)

**Comment by alonp99** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-team-6440578ab73f8300121198b9/issues/ballerine-io/ballerine/986?planning-poker) with Zenhub @alonp99
