### ISSUE TITLE
Add `collection_flow` indicator

### ISSUE THREAD

**Issue by Omri-Levy** [ballerine-io/ballerine#997]
- [ ] Use `context.entity.data.__isFinished` and display a badge of "Pending End-user Input" when false

**Comment by tomer-shvadron** [comment]
1. Is it only for KYC block or for non-KYC block as well?
2. is the `__isFinished` flag set to true only at the end of the entire collection flow?
3. Where should I display the badge? In case status, in a specific block or on all blocks?
4. Ask Alon and Nitzan - should we create a state for data collection that we could tag?

**Comment by tomer-shvadron** [comment]
Depends on #1018
